FROM nvcr.io/nvidia/pytorch:20.11-py3

RUN echo $TORCH_CUDA_ARCH_LIST $TORCH_NVCC_FLAGS 
ENV TORCH_CUDA_ARCH_LIST="8.0 8.6+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Need to remove the default opencv (for reasons I don't understand we get double installs otherwise)
RUN pip uninstall -y opencv-python

ARG PYTORCH
ARG MMCV="1.6.1"
ARG MMDET="2.25.2"
ARG MMSEG="0.28.0"
# Install MMCV from source
RUN git clone --branch v${MMCV} https://github.com/open-mmlab/mmcv.git /mmcv
RUN cd /mmcv && MMCV_WITH_OPS=1 pip install -e .
# Install MMDetection from source
RUN git clone --branch v${MMDET} https://github.com/open-mmlab/mmdetection.git /mmdetection
RUN cd /mmdetection && pip install -v -e .
# Install MMsegmentation from pip (for now)
RUN pip install --no-cache-dir mmsegmentation==${MMSEG}

# Install MMDetection3D
RUN pip install dataclass-wizard h5py open3d --ignore-installed PyYAML
COPY . /mmdetection3d
WORKDIR /mmdetection3d
ENV FORCE_CUDA="1"
RUN pip install -r requirements/build.txt
RUN pip install --no-cache-dir -e . --ignore-installed llvmlite
ENV PYTHONPATH='.:./agp'
